export const positions = [
  'GK',
  'RB',
  'RWB',
  'CB',
  'LB',
  'LWB',
  'RM',
  'CDM',
  'CM',
  'CAM',
  'LM',
  'RW',
  'CF',
  'ST',
  'LW'
]

export const matchPositions = {
  GK: 'DEF',
  LB: 'DEF',
  LWB: 'DEF',
  LCB: 'DEF',
  CB: 'DEF',
  RCB: 'DEF',
  RB: 'DEF',
  RWB: 'DEF',
  LM: 'MID',
  LDM: 'MID',
  LCM: 'MID',
  CDM: 'MID',
  CM: 'MID',
  RDM: 'MID',
  RCM: 'MID',
  RM: 'MID',
  LAM: 'MID',
  CAM: 'MID',
  RAM: 'MID',
  LW: 'ATT',
  CF: 'ATT',
  LS: 'ATT',
  ST: 'ATT',
  RS: 'ATT',
  RW: 'ATT'
}

export const nationalities = {
  // Africa
  'Algeria': 'dz',
  'Angola': 'ao',
  'Benin': 'bj',
  'Botswana': 'bw',
  'Burkina Faso': 'bf',
  'Burundi': 'bi',
  'Cameroon': 'cm',
  'Cape Verde': 'cv',
  'Central African Republic': 'cf',
  'Chad': 'td',
  'Comoros': 'km',
  'Congo': 'cg',
  'Djibouti': 'dj',
  'DR Congo': 'cd',
  'Egypt': 'eg',
  'Equatorial Guinea': 'gq',
  'Eritrea': 'er',
  'Eswatini': 'sz',
  'Ethiopia': 'et',
  'Gabon': 'ga',
  'Gambia': 'gm',
  'Ghana': 'gh',
  'Guinea': 'gn',
  'Guinea Bissau': 'gw',
  'Ivory Coast': 'ci',
  'Kenya': 'ke',
  'Lesotho': 'ls',
  'Liberia': 'lr',
  'Libya': 'ly',
  'Madagascar': 'mg',
  'Malawi': 'mw',
  'Mali': 'ml',
  'Mauritania': 'mr',
  'Mauritius': 'mu',
  'Morocco': 'ma',
  'Mozambique': 'mz',
  'Namibia': 'na',
  'Niger': 'ne',
  'Nigeria': 'ng',
  'Rwanda': 'rw',
  'Senegal': 'sn',
  'Seychelles': 'sc',
  'Sierra Leone': 'sl',
  'Somalia': 'so',
  'South Africa': 'za',
  'South Sudan': 'ss',
  'Sudan': 'sd',
  'São Tomé and Príncipe': 'st',
  'Tanzania': 'tz',
  'Togo': 'tg',
  'Tunisia': 'tn',
  'Uganda': 'ug',
  'Zambia': 'zm',
  'Zimbabwe': 'zw',

  // Asia
  'Afghanistan': 'af',
  'Armenia': 'am',
  'Azerbaijan': 'az',
  'Bahrain': 'bh',
  'Bangladesh': 'bd',
  'Bhutan': 'bt',
  'Brunei Darussalem': 'bn',
  'Cambodia': 'kh',
  'China PR': 'cn',
  'Chinese Taipei': 'tw',
  'Georgia': 'ge',
  'Hong Kong': 'hk',
  'India': 'in',
  'Indonesia': 'id',
  'Iran': 'ir',
  'Iraq': 'iq',
  'Israel': 'il',
  'Japan': 'jp',
  'Jordan': 'jo',
  'Kazakhstan': 'kz',
  'Korea DPR': 'kp',
  'Korea Republic': 'kr',
  'Kuwait': 'kw',
  'Kyrgyzstan': 'kg',
  'Laos': 'la',
  'Lebanon': 'lb',
  'Macau': 'mo',
  'Malaysia': 'my',
  'Maldives': 'mv',
  'Mongolia': 'mn',
  'Myanmar': 'mm',
  'Nepal': 'np',
  'Oman': 'om',
  'Pakistan': 'pk',
  'Palestine': 'ps',
  'Philippines': 'ph',
  'Qatar': 'qa',
  'Saudi Arabia': 'sa',
  'Singapore': 'sg',
  'Sri Lanka': 'lk',
  'Syria': 'sy',
  'Tajikistan': 'tj',
  'Thailand': 'th',
  'Timor-Leste': 'tl',
  'Turkey': 'tr',
  'Turkmenistan': 'tm',
  'United Arab Emirates': 'ae',
  'Uzbekistan': 'uz',
  'Vietnam': 'vn',
  'Yemen': 'ye',

  // Europe
  'Albania': 'al',
  'Andorra': 'ad',
  'Austria': 'at',
  'Belarus': 'by',
  'Belgium': 'be',
  'Bosnia & Herzegovina': 'ba',
  'Bulgaria': 'bg',
  'Croatia': 'hr',
  'Cyprus': 'cy',
  'England': 'gb-eng',
  'Estonia': 'ee',
  'Faroe Islands': 'fo',
  'Finland': 'fi',
  'France': 'fr',
  'Germany': 'de',
  'Gibraltar': 'gi',
  'Greece': 'gr',
  'Hungary': 'hu',
  'Iceland': 'is',
  'Italy': 'it',
  'Kosovo': 'xk',
  'Latvia': 'lv',
  'Liechtenstein': 'li',
  'Lithuania': 'lt',
  'Luxembourg': 'lu',
  'Malta': 'mt',
  'Moldova': 'md',
  'Montenegro': 'me',
  'Netherlands': 'nl',
  'North Macedonia': 'mk',
  'Northern Ireland': 'gb-nir',
  'Norway': 'no',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Republic of Ireland': 'ie',
  'Romania': 'ro',
  'Russia': 'ru',
  'San Marino': 'sm',
  'Scotland': 'gb-sct',
  'Serbia': 'rs',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'Spain': 'es',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Ukraine': 'ua',
  'Wales': 'gb-wls',

  // North America
  'Anguilla': 'ai',
  'Antigua & Barbuda': 'ag',
  'Bahamas': 'bs',
  'Barbados': 'bb',
  'Belize': 'bz',
  'Bermuda': 'bm',
  'British Virgin Isles': 'vg',
  'Canada': 'ca',
  'Cayman Islands': 'ky',
  'Costa Rica': 'cr',
  'Cuba': 'cu',
  'Czech Republic': 'cz',
  'Denmark': 'dk',
  'Dominica': 'dm',
  'Dominican Republic': 'do',
  'El Salvador': 'sv',
  'Greenland': 'gl',
  'Grenada': 'gd',
  'Guatemala': 'gt',
  'Haiti': 'ht',
  'Honduras': 'hn',
  'Jamaica': 'jm',
  'Mexico': 'mx',
  'Montserrat': 'ms',
  'Nicaragua': 'ni',
  'Panama': 'pa',
  'Puerto Rico': 'pr',
  'St Kitts Nevis': 'kn-sk',
  'St Lucia': 'lc',
  'St Vincent Grenadine': 'vc',
  'Turks & Caicos': 'tc',
  'United States': 'us',
  'US Virgin Islands': 'vi',

  // South America
  'Argentina': 'ar',
  'Aruba': 'aw',
  'Bolivia': 'bo',
  'Brazil': 'br',
  'Chile': 'cl',
  'Colombia': 'co',
  'Curaçao': 'cw',
  'Ecuador': 'ec',
  'Guyana': 'gy',
  'Paraguay': 'py',
  'Peru': 'pe',
  'Suriname': 'sr',
  'Trinidad & Tobago': 'tt',
  'Uruguay': 'uy',
  'Venezuela': 've',

  // Oceania
  'American Samoa': 'as',
  'Australia': 'au',
  'Cook Islands': 'ck',
  'Fiji': 'fj',
  'Guam': 'gu',
  'New Caledonia': 'nc',
  'New Zealand': 'nz',
  'Papua New Guinea': 'pg',
  'Samoa': 'ws',
  'Solomon Islands': 'sb',
  'Tahiti': 'pf',
  'Tonga': 'to',
  'Vanuatu': 'vu'
}
